"use client";
import { useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowUpRight } from "lucide-react";

const EASE = [0.22, 1, 0.36, 1] as const;
const email = "sales@futurepointt.com", phone = "+92 42 5846691-2";
const socials = [["LinkedIn", "https://www.linkedin.com/company/future-point-technologies"], ["X / Twitter", "https://twitter.com/FuturePoint17"], ["Facebook", "https://www.facebook.com/profile.php?id=100084498926966"], ["YouTube", "https://www.youtube.com/channel/UCcpGKTYiQkdcQW6U8p3MSHA"]] as const;
const offices = [{ city: "Lahore", type: "Head Office", address: "19A, Ahmad Block Garden Town Lahore" }, { city: "Karachi", type: "Karachi Branch Office", address: "A-2/3 West Land Trade Center, Jinnah Housing Society PECHS, Shahrah-e-Faisal Karachi" }, { city: "Islamabad", type: "Islamabad Branch Office", address: "Office number 312, 3rd floor Lord Trade Center F11, Markaz Islamabad" }, { city: "Dubai", type: "Dubai Office", address: "FPS Technologies L.L.C., PO Box 237798, Dubai, United Arab Emirates" }] as const;
function ContactRow({ label, value, href, action }: { label: string; value: string; href: string; action: string }) { return <a href={href} className="group grid gap-3 border-b border-white/20 py-6 transition-colors hover:border-white/50 sm:grid-cols-[130px_1fr_auto] sm:items-center"><span className="text-xs font-semibold uppercase tracking-[.18em] text-lime">{label}</span><span className="text-xl font-semibold tracking-[-.025em] text-white sm:text-2xl">{value}</span><span className="inline-flex items-center gap-2 text-sm text-white/55">{action}<ArrowUpRight className="size-4 text-white/55" /></span></a>; }
function PlatformIcon({ label }: { label: string }) { return <svg viewBox="0 0 24 24" className="size-5 text-white/55" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true">{label === "LinkedIn" ? <><rect x="3" y="3" width="18" height="18" rx="2" /><path d="M7 10v7m0-10v.01M11 17v-4a2 2 0 0 1 4 0v4" /></> : label === "Facebook" ? <path d="M15 3h-3a4 4 0 0 0-4 4v3H5v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" /> : label === "YouTube" ? <><rect x="3" y="6" width="18" height="12" rx="3" /><path d="m10 9.5 5 2.5-5 2.5z" /></> : <><path d="M4 4l16 16M20 4 4 20" /></>}</svg>; }
export function ContactExperience() { const reduce = useReducedMotion(); const [index, setIndex] = useState(0); const active = offices[index]; const direction = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(active.address)}`; const reveal = { initial: { opacity: 0, y: reduce ? 0 : 12 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .2 }, transition: { duration: reduce ? 0 : .6, ease: EASE } }; return <>
  <section className="relative overflow-hidden rounded-b-[24px] bg-charcoal-deep px-5 pb-16 pt-[120px] text-white sm:px-8 lg:px-12 lg:pb-20 lg:pt-[140px]"><div className="hero-motif" aria-hidden="true"><div className="hero-motif__dots" /></div><div className="relative z-10 mx-auto max-w-[1440px]"><motion.div {...reveal}><p className="eyebrow">Contact Future Point</p><h1 className="mt-5 max-w-[14ch] text-[clamp(3.25rem,5.5vw,5.25rem)] font-semibold leading-[.94] tracking-[-.055em]">Let&apos;s start a conversation.</h1><p className="mt-7 max-w-[48ch] text-lg leading-8 text-white/65">Talk to Future Point about your technology requirements, services, support or upcoming initiatives.</p></motion.div><motion.div {...reveal} transition={{ duration: reduce ? 0 : .6, delay: reduce ? 0 : .1, ease: EASE }} className="mt-12 max-w-[920px]"><ContactRow label="Email" value={email} href={`mailto:${email}`} action="Email us" /><ContactRow label="Phone" value={phone} href="tel:+924258466912" action="Call us" /></motion.div></div></section>
  <section className="px-5 py-20 sm:px-8 sm:py-24 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px]"><motion.div {...reveal}><p className="eyebrow">Our offices</p><h2 className="chapter-title mt-5 max-w-[14ch]">Three cities. One Future Point.</h2><p className="mt-6 max-w-[46ch] text-lg leading-8 text-muted-foreground">Connect with our teams in Lahore, Karachi and Islamabad.</p></motion.div><div className="mt-14 hidden border-t border-charcoal/15 lg:grid lg:grid-cols-[1.25fr_.75fr] lg:gap-16"><div>{offices.map((office, i) => <button type="button" key={office.city} onClick={() => setIndex(i)} className={`group flex w-full cursor-pointer items-center justify-between border-b border-charcoal/15 py-6 text-left focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-lime ${index === i ? "text-charcoal" : "text-charcoal/45"}`}><span className="text-[clamp(2.2rem,4.4vw,4.5rem)] font-semibold leading-none tracking-[-.055em] transition-transform group-hover:translate-x-1">{office.city}</span><span className={`font-mono text-xs ${index === i ? "text-lime-dark" : "text-charcoal/35"}`}>0{i + 1}</span></button>)}</div><div className="border-b border-charcoal/15 py-10"><AnimatePresence mode="wait"><motion.div key={active.city} initial={{ opacity: 0, y: reduce ? 0 : 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: reduce ? 0 : -8 }} transition={{ duration: reduce ? 0 : .28, ease: EASE }}><p className="text-xs font-semibold uppercase tracking-[.18em] text-lime-dark">{active.type}</p><h3 className="mt-6 text-4xl font-semibold tracking-[-.05em] text-charcoal">{active.city}</h3><p className="mt-6 max-w-[28ch] text-lg leading-8 text-muted-foreground">{active.address}</p><a href={direction} target="_blank" rel="noreferrer" className="group mt-10 inline-flex items-center gap-2 text-sm font-semibold text-charcoal hover:text-lime-dark">Get directions<ArrowUpRight className="size-4 text-charcoal" /></a></motion.div></AnimatePresence></div></div><div className="mt-10 border-t border-charcoal/15 lg:hidden">{offices.map(office => <div key={office.city} className="border-b border-charcoal/15 py-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-lime-dark">{office.type}</p><h3 className="mt-4 text-3xl font-semibold tracking-[-.04em] text-charcoal">{office.city}</h3><p className="mt-4 max-w-[30ch] text-base leading-7 text-muted-foreground">{office.address}</p><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(office.address)}`} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-charcoal hover:text-lime-dark">Get directions<ArrowUpRight className="size-4 text-charcoal" /></a></div>)}</div></div></section>
  <section className="bg-offwhite px-3 py-8 sm:px-4 lg:px-6"><div className="relative overflow-hidden rounded-[24px] bg-charcoal-deep px-5 py-16 text-white sm:px-8 sm:py-20 lg:px-12"><div className="hero-motif" aria-hidden="true"><div className="hero-motif__dots" /></div><div className="relative z-10 mx-auto max-w-[1440px]"><p className="eyebrow">Connect</p><h2 className="mt-5 max-w-[14ch] text-4xl font-semibold leading-[1.03] tracking-[-.04em] sm:text-5xl">Stay connected with Future Point.</h2><p className="mt-6 max-w-[46ch] text-lg leading-8 text-white/65">Follow Future Point for company updates, technology insights, projects and industry news.</p><div className="mt-10 grid border-t border-white/20 sm:grid-cols-2">{socials.map(([label, href], i) => <a key={label} href={href} target="_blank" rel="noopener noreferrer" className={`group flex items-center justify-between border-b border-white/20 py-5 text-lg font-semibold transition-colors hover:text-lime ${i % 2 ? "sm:border-l sm:pl-7" : "sm:pr-7"}`}><span className="flex items-center gap-3"><PlatformIcon label={label} />{label}</span><ArrowUpRight className="size-5 text-white/55" /></a>)}</div></div></div></section>
</>; }
